site_name: zend-config-aggregator-parameters
docs_dir: docs/book
site_dir: docs/html
pages:
    - index.md
    - Usage: usage.md
site_description: 'PostProcessor extension for zendframework/zend-config-aggregator to allow usage of templated parameters within your configuration'
repo_url: 'https://github.com/zendframework/zend-config-aggregator-parameters'
copyright: 'Copyright (c) 2018 <a href="https://www.zend.com/">Zend Technologies USA Inc.</a>'
